### ISSUE TITLE
How can I validate a field based on another field?

### ISSUE THREAD

**Issue by lukebitts** [jaspervdj/digestive-functors#128]
I'm trying to have a registration form with fields like `email` and `emailConfirmation`, or `password` and `passwordConfirmation`. Validating `email` and `password` is easy, there are rules and I've written the respective functions.

The other two are harder though. I found this [question][1] and tried writing my code like this:

The form definition, using Blaze:

    registrationForm :: (View Html) -> Html
    registrationForm view = docTypeHtml $ do
      form ! name "registration" ! method "post" ! action "/register" $ do
        fieldset $ do
          label ! for "password" $ (text "Password")
          inputText "password" view
          errorList "password" view

          br

          label ! for "passwordConfirmation" $ (text "Password Confirmation")
          inputText "passwordConfirmation" view
          errorList "passwordConfirmation" view

and the validator:

    data Password = Password { password :: Text }

    validateForm :: Monad m => Form Html m Password
    validateForm =
      Password
        <$> "password" .: validatePassword
      where
        validatePassword =
          validate fst' $ (,) <$> ("password"             .: D.text Nothing)
                              <*> ("passwordConfirmation" .: D.text Nothing)
        fst' (p1, p2) | p1 == p2  = Success p1
                      | otherwise = Error "Passwords must match"

But whenever I run the server I get a message saying "password is not a field". If I remove the validation and give `password` a simple validation, then it works as expected. Am I missing something here?

  [1]: http://stackoverflow.com/questions/12106964/validation-spanning-multiple-fields

**Comment by cimmanon** [comment]
Your validateForm contains a subForm by the name of "password" that has the fields of "password" and "passwordContainer".  I'm not familiar with Blaze, but there should be a function for running the contents of a subform.

**Comment by lukebitts** [comment]
Do you have an example in another framework? I can't find anything about subforms in Blaze.

**Comment by cimmanon** [comment]
Sorry, the function you're looking for should be called something like `subView`.  I use [Heist](https://jaspervdj.be/posts/2012-04-03-digestive-functors-for-snap-users.html), and the splice we use is called `dfSubView`.  Maybe the [Blaze example](https://jaspervdj.be/posts/2012-03-21-digestive-functors-0.3.html) will help?

**Comment by lukebitts** [comment]
Thanks @cimmanon, the link helped. For future reference, this is what I had to do:

```
registrationForm :: (View Html) -> Html
registrationForm view = docTypeHtml $ do
  form ! name "registration" ! method "post" ! action "/register" $ do
    fieldset $ do
      inputText "password.p1" view
      br
      inputText "password.p2" view
      errorList "password" view
```

```
data Password = Password { password :: Text }

validateForm :: Monad m => Form Html m Password
validateForm =
  Password
    <$> "password" .: validatePassword
  where
    validatePassword =
      validate fst' $ (,) <$> ("p1" .: D.text Nothing)
                          <*> ("p2" .: D.text Nothing)
    fst' (p1, p2) | p1 == p2  = Success p1
                  | otherwise = Error "Passwords must match"
```
